---
- name: Déploiement sur K3d
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Créer le namespace
      kubernetes.core.k8s:
        name: demo-ansible
        api_version: v1
        kind: Namespace
        state: present

    - name: Créer le Deployment Nginx
      kubernetes.core.k8s:
        namespace: demo-ansible
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-custom-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx-custom
            template:
              metadata:
                labels:
                  app: nginx-custom
              spec:
                containers:
                - name: nginx
                  image: nginx-custom:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 80

    - name: Créer le Service
      kubernetes.core.k8s:
        namespace: demo-ansible
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-custom-service
          spec:
            selector:
              app: nginx-custom
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: NodePort